[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
python_classes = Test*
addopts = -v --cov=crawler --cov=geps_crawler.py --cov=config.py --cov=services --cov=repositories --cov=queue --cov-report=term-missing --cov-fail-under=10 --no-cov-on-fail
asyncio_mode = auto
