#!/usr/bin/env python
"""
バックフィル品質レポート生成スクリプト

バックフィル実行後の品質メトリクスを集計し、Markdown/JSON形式でレポートを出力する。
"""
import sys
import json
from datetime import datetime, timedelta
from pathlib import Path

from database.session import get_db
from database.models import Bid, BackfillJob, BackfillJobLog
from services.backfill_dedup import BackfillDedupService


def generate_markdown_report(report: dict, job_id: int = None) -> str:
    """Markdown形式のレポートを生成"""
    lines = []
    lines.append("# バックフィル品質レポート")
    lines.append("")
    lines.append(f"**生成日時**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC")
    if job_id:
        lines.append(f"**対象ジョブ**: #{job_id}")
    lines.append("")

    if job_id and "job" in report:
        job = report["job"]
        lines.append("## ジョブ情報")
        lines.append("")
        lines.append(f"- **ジョブID**: {job['id']}")
        lines.append(f"- **機関ID**: {job['agency_id']}")
        lines.append(f"- **期間**: {job['start_date']} 〜 {job['end_date']}")
        lines.append(f"- **ステータス**: {job['status']}")
        lines.append(f"- **取得件数**: {job['fetched_count']:,}")
        lines.append(f"- **新規件数**: {job['new_count']:,}")
        lines.append(f"- **更新件数**: {job['updated_count']:,}")
        lines.append(f"- **エラー件数**: {job['error_count']:,}")
        lines.append("")

        if "records" in report:
            lines.append("## 取得レコード品質")
            lines.append("")
            lines.append(f"- **総レコード数**: {report['records']:,}")
            lines.append("")
            lines.append("### 必須フィールド欠落状況")
            lines.append("")
            for field, count in report.get("missing_fields", {}).items():
                pct = (count / report['records'] * 100) if report['records'] > 0 else 0
                lines.append(f"- **{field}**: {count:,} 件 ({pct:.1f}%)")
            lines.append("")

    elif "overall" in report:
        overall = report["overall"]
        lines.append("## 全体データ整合性")
        lines.append("")
        lines.append(f"- **重複グループ数**: {overall.get('duplicate_groups', 0):,}")
        lines.append(f"- **重複総件数**: {overall.get('duplicate_total', 0):,}")
        lines.append(f"- **source_url未設定**: {overall.get('null_source_url', 0):,}")
        lines.append("")
        lines.append("### 必須フィールド欠落")
        lines.append("")
        for key, val in overall.items():
            if key.startswith("missing_"):
                field = key.replace("missing_", "")
                lines.append(f"- **{field}**: {val:,} 件")
        lines.append("")

        if "anomalies" in overall and overall["anomalies"]:
            lines.append("## 異常値検出")
            lines.append("")
            for rule, anomalies in overall["anomalies"].items():
                lines.append(f"### {rule}")
                lines.append("")
                lines.append(f"検出件数: {len(anomalies)}")
                lines.append("")
                for a in anomalies[:10]:  # 最初の10件のみ表示
                    lines.append(f"- ID={a['id']}: {a['value']}")
                if len(anomalies) > 10:
                    lines.append(f"- ... 他 {len(anomalies) - 10} 件")
                lines.append("")

    lines.append("---")
    lines.append("*Generated by backfill quality report generator*")
    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="バックフィル品質レポート生成")
    parser.add_argument("--job-id", type=int, help="特定ジョブIDのレポート生成")
    parser.add_argument("--output", type=str, help="出力ファイルパス")
    parser.add_argument("--format", choices=["md", "json"], default="md", help="出力形式")
    args = parser.parse_args()

    service = BackfillDedupService()

    try:
        if args.job_id:
            report = service.generate_quality_report(args.job_id)
        else:
            report = service.generate_quality_report()

        if args.format == "json":
            output = json.dumps(report, indent=2, ensure_ascii=False)
        else:
            output = generate_markdown_report(report, args.job_id)

        if args.output:
            Path(args.output).write_text(output, encoding="utf-8")
            print(f"レポートを保存: {args.output}")
        else:
            print(output)

        return 0

    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())